<a href="https://colab.research.google.com/github/OMatheusWander/SCTEC/blob/main/Aula_1_SCTEC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%sql --output orders

SELECT * FROM orders limit 10;

 * sqlite:///aula03_ecommerce.db
Done.

KeyError: 'DEFAULT'

In [ ]:
!pip -q install ipython-sql

import pandas as pd
import sqlite3

customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")

con = sqlite3.connect("aula03_ecommerce.db")

customers.to_sql("customers", con, if_exists="replace", index=False)
orders.to_sql("orders", con, if_exists="replace", index=False)
order_items.to_sql("order_items", con, if_exists="replace", index=False)

con.close()

%load_ext sql
%sql sqlite:///aula03_ecommerce.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
import sqlite3
import pandas as pd

# Establish a connection to the database
con = sqlite3.connect("aula03_ecommerce.db")

# Execute the SQL query and load results directly into a pandas DataFrame
orders_df = pd.read_sql_query("SELECT * FROM orders limit 10;", con)

# Close the connection
con.close()

# Display the DataFrame
orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,o00001,c0089,shipped,2025-06-19 15:02:00,None,2025-07-02 15:02:00
1,o00002,c0212,delivered,2025-06-22 09:37:00,2025-07-09 09:37:00,2025-07-05 09:37:00
2,o00003,c0205,delivered,2025-06-29 16:36:00,2025-07-13 16:36:00,2025-07-14 16:36:00
3,o00004,c0027,delivered,2025-01-27 17:28:00,2025-02-13 17:28:00,2025-02-07 17:28:00
4,o00005,c0074,delivered,2025-06-30 21:57:00,2025-07-09 21:57:00,2025-07-11 21:57:00
5,o00006,c0130,delivered,2025-03-08 10:05:00,2025-03-10 10:05:00,2025-03-19 10:05:00
6,o00007,c0143,delivered,2025-06-07 15:44:00,2025-06-09 15:44:00,2025-06-20 15:44:00
7,o00008,c0048,delivered,2025-07-28 09:56:00,2025-08-01 09:56:00,2025-08-12 09:56:00
8,o00009,c0089,delivered,2025-08-17 13:38:00,2025-08-26 13:38:00,2025-08-26 13:38:00
9,o00010,c0064,delivered,2025-10-05 11:54:00,2025-10-15 11:54:00,2025-10-20 11:54:00

In [ ]:
con = sqlite3.connect("aula03_ecommerce.db")

# Execute the SQL query and load results directly into a pandas DataFrame
columns_3 = pd.read_sql_query("SELECT order_status, order_purchase_timestamp,order_id FROM orders limit 10;", con)

# Close the connection
con.close()

# Display the DataFrame
columns_3

  order_status order_purchase_timestamp order_id
0      shipped      2025-06-19 15:02:00   o00001
1    delivered      2025-06-22 09:37:00   o00002
2    delivered      2025-06-29 16:36:00   o00003
3    delivered      2025-01-27 17:28:00   o00004
4    delivered      2025-06-30 21:57:00   o00005
5    delivered      2025-03-08 10:05:00   o00006
6    delivered      2025-06-07 15:44:00   o00007
7    delivered      2025-07-28 09:56:00   o00008
8    delivered      2025-08-17 13:38:00   o00009
9    delivered      2025-10-05 11:54:00   o00010

In [ ]:
con = sqlite3.connect("aula03_ecommerce.db")

pedidos_entregues = pd.read_sql_query("SELECT * FROM orders WHERE order_status = 'delivered';", con)

con.close()

pedidos_entregues

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,o00002,c0212,delivered,2025-06-22 09:37:00,2025-07-09 09:37:00,2025-07-05 09:37:00
1,o00003,c0205,delivered,2025-06-29 16:36:00,2025-07-13 16:36:00,2025-07-14 16:36:00
2,o00004,c0027,delivered,2025-01-27 17:28:00,2025-02-13 17:28:00,2025-02-07 17:28:00
3,o00005,c0074,delivered,2025-06-30 21:57:00,2025-07-09 21:57:00,2025-07-11 21:57:00
4,o00006,c0130,delivered,2025-03-08 10:05:00,2025-03-10 10:05:00,2025-03-19 10:05:00
...,...,...,...,...,...,...
449,o00555,c0144,delivered,2025-02-20 21:39:00,2025-02-23 21:39:00,2025-03-01 21:39:00
450,o00556,c0132,delivered,2025-06-10 10:14:00,2025-06-18 10:14:00,2025-06-16 10:14:00
451,o00557,c0049,delivered,2025-01-27 09:28:00,2025-02-14 09:28:00,2025-02-02 09:28:00
452,o00559,c0018,delivered,2025-01-03 11:14:00,2025-01-16 11:14:00,2025-01-09 11:14:00
453,o00560,c0021,delivered,2025-09-20 12:07:00,2025-10-02 12:07:00,2025-09-27 12:07:00

In [ ]:
import sqlite3
import pandas as pd

# Establish a connection to the database
con = sqlite3.connect("aula03_ecommerce.db")

# Execute the SQL query and load results directly into a pandas DataFrame
all_orders_df = pd.read_sql_query("SELECT * FROM orders;", con)

# Close the connection
con.close()

# Display the DataFrame
all_orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,o00001,c0089,shipped,2025-06-19 15:02:00,None,2025-07-02 15:02:00
1,o00002,c0212,delivered,2025-06-22 09:37:00,2025-07-09 09:37:00,2025-07-05 09:37:00
2,o00003,c0205,delivered,2025-06-29 16:36:00,2025-07-13 16:36:00,2025-07-14 16:36:00
3,o00004,c0027,delivered,2025-01-27 17:28:00,2025-02-13 17:28:00,2025-02-07 17:28:00
4,o00005,c0074,delivered,2025-06-30 21:57:00,2025-07-09 21:57:00,2025-07-11 21:57:00
...,...,...,...,...,...,...
555,o00556,c0132,delivered,2025-06-10 10:14:00,2025-06-18 10:14:00,2025-06-16 10:14:00
556,o00557,c0049,delivered,2025-01-27 09:28:00,2025-02-14 09:28:00,2025-02-02 09:28:00
557,o00558,c0104,processing,2025-12-30 15:25:00,None,2026-01-12 15:25:00
558,o00559,c0018,delivered,2025-01-03 11:14:00,2025-01-16 11:14:00,2025-01-09 11:14:00
559,o00560,c0021,delivered,2025-09-20 12:07:00,2025-10-02 12:07:00,2025-09-27 12:07:00

In [ ]:
all_orders_df = pd.read_sql_query("SELECT * FROM orders;", con)

all_orders_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,o00001,c0089,shipped,2025-06-19 15:02:00,None,2025-07-02 15:02:00
1,o00002,c0212,delivered,2025-06-22 09:37:00,2025-07-09 09:37:00,2025-07-05 09:37:00
2,o00003,c0205,delivered,2025-06-29 16:36:00,2025-07-13 16:36:00,2025-07-14 16:36:00
3,o00004,c0027,delivered,2025-01-27 17:28:00,2025-02-13 17:28:00,2025-02-07 17:28:00
4,o00005,c0074,delivered,2025-06-30 21:57:00,2025-07-09 21:57:00,2025-07-11 21:57:00
...,...,...,...,...,...,...
555,o00556,c0132,delivered,2025-06-10 10:14:00,2025-06-18 10:14:00,2025-06-16 10:14:00
556,o00557,c0049,delivered,2025-01-27 09:28:00,2025-02-14 09:28:00,2025-02-02 09:28:00
557,o00558,c0104,processing,2025-12-30 15:25:00,None,2026-01-12 15:25:00
558,o00559,c0018,delivered,2025-01-03 11:14:00,2025-01-16 11:14:00,2025-01-09 11:14:00
559,o00560,c0021,delivered,2025-09-20 12:07:00,2025-10-02 12:07:00,2025-09-27 12:07:00

In [ ]:
%sql sqlite:///aula03_ecommerce.db

%%sql
SELECT * FROM orders LIMIT 5;

SyntaxError: invalid syntax (3819008502.py, line 4)

In [ ]:
%%sql --style plain
SELECT *
FROM orders
LIMIT 5

 * sqlite:///aula03_ecommerce.db
Done.

KeyError: 'DEFAULT'

In [ ]:
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

%config SqlMagic.autopandas = True

In [ ]:
%%sql
SELECT *
FROM orders
LIMIT 5

 * sqlite:///aula03_ecommerce.db
Done.

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,o00001,c0089,shipped,2025-06-19 15:02:00,None,2025-07-02 15:02:00
1,o00002,c0212,delivered,2025-06-22 09:37:00,2025-07-09 09:37:00,2025-07-05 09:37:00
2,o00003,c0205,delivered,2025-06-29 16:36:00,2025-07-13 16:36:00,2025-07-14 16:36:00
3,o00004,c0027,delivered,2025-01-27 17:28:00,2025-02-13 17:28:00,2025-02-07 17:28:00
4,o00005,c0074,delivered,2025-06-30 21:57:00,2025-07-09 21:57:00,2025-07-11 21:57:00